# datasource
spring.datasource.url=jdbc:h2:~/demo:demodb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.enabled-by-default=false
management.endpoint.info.enabled=true
management.endpoint.loggers.enabled=true
management.endpoint.health.enabled=true
management.endpoint.configprops.enabled=true
management.endpoints.web.exposure.include=loggers,info,health,configprops
